sonar.projectKey=itz-prashant_e-com-auth-service
soanr.organization=itz-prashant
sonar.projectName=e-com-auth-service
sonar.source=src
sonar.test=tests
sonar.exclusion=**/node_modules/**/*, **/dist/**/*, **/build/**/*, **/migration/**/*
sonar.qualitygate.wait=true
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.scm.exclusion.disabled=true