sonar.projectKey=itz-prashant_e-com-auth-service
sonar.organization=itz-prashant
sonar.projectName=e-com-auth-service
sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/node_modules/**/*, **/dist/**/*, **/build/**/*, **/migration/**/*
sonar.qualitygate.wait=true
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.scm.exclusion.disabled=true